# Generated by Django 4.1 on 2022-09-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_alter_activity_options_activity_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
    ]
